# Notebook for loading in the AMASS data

In [1]:
import utils
import numpy as np

In [2]:
# You can load the files as a mesh. For example:
# datasets/action_smplx_models/male2_Calibration_stagii.npz
mesh = utils.mesh_from_path("datasets/action_smplx_models/male_run.npz", idx = 0) # each frame has its own mesh, the idx is the frame number

In [3]:
# Now that you have a mesh, you can access the vertices and faces
print(mesh.vertices, mesh.faces)

[[ 3.18930244 -3.30554485  1.45028448]
 [ 3.18586087 -3.30781889  1.44871616]
 [ 3.18552446 -3.30812502  1.45000625]
 ...
 [ 3.21696854 -3.18069506  1.46562254]
 [ 3.21605539 -3.182863    1.46635187]
 [ 3.2147119  -3.18484497  1.46695638]] [[    3     1     0]
 [    7     5     4]
 [   12    14    13]
 ...
 [ 9944 10097 10084]
 [ 9940 10084 10071]
 [10071 10058  9932]]


In [4]:
# the plot_arr function is made to plot these point clouds
utils.plot_arr(mesh.vertices)

In [5]:
# the vertices are static, but you can also sample random points on the mesh
random_sampled_points = utils.sampled_verts_from_mesh(mesh, n_points = 1000, return_faces = False) # set return_faces to True if you need the face index that each point was sampled from
utils.plot_arr(random_sampled_points)