# Notebook for loading in the AMASS data

In [1]:
import utils
import numpy as np

In [ ]:
# You can load the files as a mesh. For example:
# datasets/action_smplx_models/male2_Calibration_stagii.npz
mesh = utils.mesh_from_path("datasets/action_smplx_models/male_run.npz", idx = 0) # each frame has its own mesh, the idx is the frame number

In [7]:
# Now that you have a mesh, you can access the vertices and faces
print(mesh.vertices, mesh.faces)

[[-0.33538309  0.09484771  1.61742377]
 [-0.33961862  0.0954667   1.61646795]
 [-0.34023634  0.09587318  1.61793959]
 ...
 [-0.23428953  0.1699869   1.63564551]
 [-0.2362884   0.168805    1.63640964]
 [-0.23850925  0.16804427  1.63711286]] [[    3     1     0]
 [    7     5     4]
 [   12    14    13]
 ...
 [ 9944 10097 10084]
 [ 9940 10084 10071]
 [10071 10058  9932]]


In [8]:
# the plot_arr function is made to plot these point clouds
utils.plot_arr(mesh.vertices)

In [11]:
# the vertices are static, but you can also sample random points on the mesh
random_sampled_points = utils.sampled_verts_from_mesh(mesh, n_points = 1000, return_faces = False) # set return_faces to True if you need the face index that each point was sampled from
utils.plot_arr(random_sampled_points)